### Import Required Libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

### Reading file

In [3]:
# read file from csv
df = pd.read_csv('Scores.csv')

In [4]:
df

    Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

In [5]:
# split X and y
X = df[['Hours']] # 2d
y = df['Scores'] #1d

In [10]:
# split data into train test 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =  train_test_split(X,y,test_size=0.1,random_state=1)

In [11]:
X_train.size

22

In [12]:
X_test.size

3

In [13]:
y_train.size

22

In [14]:
y_test.size

3

In [15]:
# importing libraries
from sklearn.linear_model import LinearRegression

# create a instance/object
lr = LinearRegression()

# fitting our model
lr.fit(X_train,y_train)

# predicting 
ypred = lr.predict(X_test)

In [18]:
X_test

    Hours
14    1.1
13    3.3
17    1.9

In [17]:
y_test

14    17
13    42
17    24
Name: Scores, dtype: int64

In [20]:
ypred

array([11.12011779, 33.38368634, 19.2159609 ])

In [29]:
X_test

    Hours
14    1.1
13    3.3
17    1.9

In [27]:
pd.DataFrame({'xtest':X_test.values.flatten(),'y_test(Actual)':y_test.values.flatten(),'ypred(Predicted)':ypred})

   xtest  y_test(Actual)  ypred(Predicted)
0    1.1              17         11.120118
1    3.3              42         33.383686
2    1.9              24         19.215961

In [32]:
# accuracy
r2_score(y_test,ypred)

0.604105492896367

### Evaluation metrics

In [33]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
#mae
mean_absolute_error(y_test,ypred)

6.426744991355382

In [34]:
#mse
mean_squared_error(y_test,ypred)

43.900302009936205

In [36]:
# rmse
np.sqrt(mean_squared_error(y_test,ypred))

np.float64(6.625730300120599)

# read this blog for loss/cost function
https://nadeemm.medium.com/cost-function-loss-function-c3cab1ddffa4